/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd;

import javax.swing.JMenu;

/**
 *
 * @author daniela
 */
/**
 * La clase Principal representa la ventana principal de la aplicación de la red social.
 */
public class Principal extends javax.swing.JFrame {
    
    private Mapa m; // Referencia al mapa de la red social
   
    /**
     * Crea una nueva instancia de la clase Principal.
     *
     * @param m La instancia de Mapa que se utilizará en la ventana principal.
     */
    public Principal(Mapa m) {
        initComponents();
        
        this.setTitle("RED SOCIAL");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.m = m;
        this.usuario.setEnabled(false);

    }

    public JMenu getUsuario() {
        return usuario;
    }

    public void setUsuario(JMenu usuario) {
        this.usuario = usuario;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarArchivo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuario = new javax.swing.JMenu();
        agregarUsuario = new javax.swing.JMenuItem();
        Eliminarusuario = new javax.swing.JMenuItem();
        verComunidad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });

        usuario.setText("Usuario");

        agregarUsuario.setText("Agregar Usuario");
        agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioActionPerformed(evt);
            }
        });
        usuario.add(agregarUsuario);

        Eliminarusuario.setText("Eliminar Usuario");
        Eliminarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarusuarioActionPerformed(evt);
            }
        });
        usuario.add(Eliminarusuario);

        verComunidad.setText("Ver Comunidad");
        verComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verComunidadActionPerformed(evt);
            }
        });
        usuario.add(verComunidad);

        jMenuBar1.add(usuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(424, 424, 424))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(CargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioActionPerformed

        new AgregarUsuario(m).setVisible(true);
    }//GEN-LAST:event_agregarUsuarioActionPerformed

    private void EliminarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarusuarioActionPerformed

        new EliminarUsuario(m).setVisible(true);
    }//GEN-LAST:event_EliminarusuarioActionPerformed

    private void verComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verComunidadActionPerformed
       
        new VerComunidad(m).setVisible(true);
    }//GEN-LAST:event_verComunidadActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed

        Cargar archivo = new Cargar(m, this);
        archivo.setVisible(true);
        archivo.setLocationRelativeTo(null);    
    }//GEN-LAST:event_CargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Mapa m = new Mapa();
        Principal a = new Principal(m);
        a.setContentPane(m);
        a.setSize(1000, 800);
        a.setLocationRelativeTo(null);

        a.setVisible(true);   
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JMenuItem Eliminarusuario;
    private javax.swing.JMenuItem agregarUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu usuario;
    private javax.swing.JMenuItem verComunidad;
    // End of variables declaration//GEN-END:variables
}
