/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author daniela
 */
/**
 * La clase RelacionAgg proporciona una interfaz gráfica para agregar nuevas relaciones entre usuarios en el mapa.
 */
public class RelacionAgg extends javax.swing.JFrame {

    Mapa m; // El mapa al que pertenece la interfaz.

    /**
     * Crea una nueva instancia de la clase RelacionAgg.
     *
     * @param m El mapa al que pertenece la interfaz.
     */
    
    public RelacionAgg(Mapa m) {
        initComponents();
        this.setTitle("AGREGAR RELACION");
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.m = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        u2 = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NuevasRelaciones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        uNuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Usuario Nuevo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, 105, 29));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Usuario al que está relacionado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        u2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u2ActionPerformed(evt);
            }
        });
        getContentPane().add(u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 99, 184, -1));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        NuevasRelaciones.setEditable(false);
        NuevasRelaciones.setColumns(20);
        NuevasRelaciones.setRows(5);
        NuevasRelaciones.setFocusable(false);
        jScrollPane1.setViewportView(NuevasRelaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 64, -1, 215));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 115, -1));

        uNuevo.setEditable(false);
        uNuevo.setFocusable(false);
        uNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(uNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 3, 158, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32456.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Screen Shot 2023-10-28 at 4.01.20 PM.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNuevoActionPerformed

    private void u2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u2ActionPerformed

    /**
     * Cuando el botón "Agregar" es presionado. Agrega una nueva relación entre usuarios.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        try {
            String Usuario1 = uNuevo.getText().trim();
            String Usuario2 = "@" + u2.getText().trim();
            Lista laux = new Lista();

            for (Arista arista : m.getArista()) {
                if (Usuario2.equals(arista.getU1()) || Usuario2.equals(arista.getU2())) {
                    laux.InsertarFinal(Usuario2);
                    break;
                } 
            }
            if(laux.getpFirst() == null){
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }
            Nodo aux = laux.getpFirst();
            while (aux != null) {
                m.getGrafo().agregarRelacion(Usuario1, aux.getDato().toString(), "");
                NuevasRelaciones.setText(Usuario1 + " sigue a " + Usuario2);
                aux = aux.getpNext();
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Algo salió mal. Por favor vuelva a intentarlo.");
        }

    }//GEN-LAST:event_agregarActionPerformed

    /**
     * Cuando el botón "Finalizar" es presionado. Oculta la ventana de agregar relaciones.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_finalizarActionPerformed

    /**
     * Obtiene el campo de texto correspondiente al usuario nuevo.
     *
     * @return El campo de texto del usuario nuevo.
     */
    public JTextField getuNuevo() {
        return uNuevo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelacionAgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelacionAgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelacionAgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelacionAgg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea NuevasRelaciones;
    private javax.swing.JButton agregar;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField u2;
    private javax.swing.JTextField uNuevo;
    // End of variables declaration//GEN-END:variables
}
